### ISSUE TITLE
Can't install plugin on Apple Silicon based mac

### ISSUE THREAD

**Issue by sammcj** [rikatz/kubepug#191]
Looks like the plugin might be build for intel only:

```
kubectl krew install deprecations
Updated the local copy of plugin index.
Updated the local copy of plugin index "kvaps".
Installing plugin: deprecations
W0829 13:50:54.381681   11235 install.go:164] failed to install plugin "deprecations": plugin "deprecations" does not offer installation for this platform
F0829 13:50:54.381735   11235 root.go:79] failed to install some plugins: [deprecations]: plugin "deprecations" does not offer installation for this platform
```

**Comment by rikatz** [comment]
https://github.com/rikatz/kubepug/commit/bcc024854f5b538aa046043d88266e449704c632

Added to go-releaser, let's see if this builds fine :)

Thanks for using the project!

**Comment by rikatz** [comment]
Hey,

I have released v1.2.2, now supporting the Apple M1 :) and the assets are there.

Can you please check and let me know?

Thanks!

**Comment by sammcj** [comment]
Thanks!

Unfortunately v1.2.2 looks to still have the issue:

```
~ kubectl krew install deprecations
Updated the local copy of plugin index.
Updated the local copy of plugin index "kvaps".
Installing plugin: deprecations
W1031 19:33:08.000406   11369 install.go:164] failed to install plugin "deprecations": plugin "deprecations" does not offer installation for this platform
F1031 19:33:08.000464   11369 root.go:79] failed to install some plugins: [deprecations]: plugin "deprecations" does not offer installation for this platform
```

```
~ kubectl krew info deprecations
NAME: deprecations
INDEX: default
VERSION: v1.2.2
HOMEPAGE: https://github.com/rikatz/kubepug
DESCRIPTION:
This plugin shows all the deprecated objects in a Kubernetes cluster allowing
the operator to verify them before upgrading the cluster. It uses the
swagger.json version available in master branch of Kubernetes repository
(github.com/kubernetes/kubernetes) as a reference. The branch can be changed
to some other desired Kubernetes version

CAVEATS:
\
 | * By default, deprecations finds deprecated object relative to the current kubernetes
 | master branch. To target a different kubernetes release, use the --k8s-version
 | argument.
 |
 | * Deprecations needs permission to GET all objects in the Cluster
/
```
